[system]
MODVersion=0
SMOOTH=1
RENDERER=1
sw_surface=0
sw_output=0
;CENTER_X=400
;CENTER_Y=250
;RESOLUTIONX = 1024
;RESOLUTIONY = 700
MMAPAMI=1
SCENCEAMI=2
KDEF_SCRIPT=1
PNG_TILE=1
PNG_LOAD_ALL=0
EXIT_GAME=1
WALK_SPEED=9
semireal=0
walk_speed2=8
fullscreen=0
simple=0
text_layer=1
zip_save=0
battle_speed=15
EFFECT_STRING=0
OPEN_MOVIE=1
KEEP_SCREEN_RATIO=1
EXPAND_GROUND=1
THREAD_READ_PNG=0
present_sync=0
FONT_VIDEOMEMERY=1

[Music]
;“Ù¡ø
VOLUME=10
VOLUMEWAV=7
SOUND3D=1
